#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
feh --bg-fill /home/degr4ne/.config/bspwm/mr-robot.jpg &
~/.config/polybar/murz/launch.sh &

ibspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

# Set margins for windows
bspc config border_width        0 
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
picom --experimental-backends &

